dist: xenial
language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install --user codecov && codecov -t CODECOV_TOKEN
script:
  - python -m pytest --cov=. --cov-report html:coverage
after_success:
  - codecov
